/**
 * Cinematic Depth Mesh Scene
 *
 * Renders an image as a depth-displaced 3D mesh with Ken Burns camera drift.
 * Uses existing depth-mesh.ts utility via R3F dynamic import.
 */

"use client";

import dynamic from "next/dynamic";
import type React from "react";
import { useMemo } from "react";
import {
  type CinematicPresetName,
  getCinematicPreset,
} from "@/lib/cinematic/scene-presets";
import { easeOutCubic } from "@/lib/storytelling/easing";
import { useSceneOverrides } from "../hooks/useSceneOverrides";
import { mergePresetWithOverrides } from "../override-utils";
import { BackgroundRenderer } from "../primitives";
import { useStorytellingStore } from "../StorytellingStore";
import type { CinematicDepthMeshData, SceneRendererProps } from "../types";

const DepthMeshLayer = dynamic(
  () =>
    import("@/lib/cinematic/depth-mesh-layer").then((m) => ({
      default: m.DepthMeshLayer,
    })),
  { ssr: false },
);

export const CinematicDepthMeshScene: React.FC<SceneRendererProps> = ({
  scene,
  progress,
  time,
  isActive,
  width,
  height,
  accentColor,
}) => {
  const data = scene.data as CinematicDepthMeshData;
  const overrides = useSceneOverrides(scene.id);

  // Resolve URLs from prerenderData (generated by orchestrator)
  const scenes = useStorytellingStore((s) => s.scenes);
  const sceneEntry = scenes.find((e) => e.scene.id === scene.id);
  const resolvedImageUrl =
    sceneEntry?.prerenderData?.imageUrl ||
    (data.imageUrl?.startsWith("GENERATE:") ? undefined : data.imageUrl);
  const resolvedDepthUrl =
    sceneEntry?.prerenderData?.depthMapUrl ||
    (data.depthUrl === "AUTO" || data.depthUrl === "auto"
      ? undefined
      : data.depthUrl);

  const basePreset = useMemo(
    () => getCinematicPreset((overrides.cinematicPreset ?? "editorial") as CinematicPresetName),
    [overrides.cinematicPreset],
  );
  const preset = useMemo(
    () => mergePresetWithOverrides(basePreset, overrides),
    [basePreset, overrides],
  );

  const textOpacity = easeOutCubic(Math.min(progress * 3, 1));
  const textSlide = (1 - easeOutCubic(Math.min(progress * 2.5, 1))) * 25;

  if (!(resolvedImageUrl && resolvedDepthUrl)) {
    return (
      <BackgroundRenderer scene={scene} width={width} height={height}>
        <div
          style={{
            width: "100%",
            height: "100%",
            backgroundColor: "#0a0a0a",
          }}
        />
      </BackgroundRenderer>
    );
  }

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "hidden",
      }}
    >
      {/* R3F Depth Mesh */}
      <div style={{ position: "absolute", inset: 0 }}>
        <DepthMeshLayer
          colorUrl={resolvedImageUrl}
          depthUrl={resolvedDepthUrl}
          preset={preset}
          progress={progress}
        />
      </div>

      {/* Subtle vignette */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          pointerEvents: "none",
          background:
            "radial-gradient(ellipse at center, transparent 55%, rgba(0,0,0,0.45) 100%)",
        }}
      />

      {/* Text overlay */}
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: 0,
          right: 0,
          padding: "40px 32px 28px",
          background: "linear-gradient(transparent, rgba(0,0,0,0.65) 40%)",
          opacity: textOpacity,
          transform: `translateY(${textSlide}px)`,
        }}
      >
        {data.headline && (
          <h2
            style={{
              margin: 0,
              fontFamily: "Georgia, serif",
              fontSize: 26,
              fontWeight: 700,
              color: "#fff",
              lineHeight: 1.25,
              textShadow: "0 2px 8px rgba(0,0,0,0.5)",
            }}
          >
            {data.headline}
          </h2>
        )}
        {data.caption && (
          <p
            style={{
              margin: "6px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 14,
              color: "rgba(255,255,255,0.75)",
              lineHeight: 1.4,
            }}
          >
            {data.caption}
          </p>
        )}
        {data.stat && (
          <div
            style={{
              marginTop: 10,
              display: "inline-block",
              padding: "5px 14px",
              background: `${accentColor}22`,
              border: `1px solid ${accentColor}44`,
              borderRadius: 4,
              fontFamily: "JetBrains Mono, monospace",
              fontSize: 20,
              fontWeight: 700,
              color: accentColor,
            }}
          >
            {data.stat}
          </div>
        )}
        {data.source && (
          <p
            style={{
              margin: "6px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 11,
              color: "rgba(255,255,255,0.4)",
              letterSpacing: "0.05em",
              textTransform: "uppercase",
            }}
          >
            Source: {data.source}
          </p>
        )}
      </div>
    </div>
  );
};
