/**
 * Cinematic Composition Scene
 *
 * Full cinematic: point cloud + particles + shader variant + headline/stat overlay.
 * The "hero" cinematic scene type — combines all engine features.
 */

"use client";

import dynamic from "next/dynamic";
import type React from "react";
import { useMemo } from "react";
import {
  type CinematicPresetName,
  getCinematicPreset,
} from "@/lib/cinematic/scene-presets";
import {
  easeInOutCubic,
  easeOutBack,
  easeOutCubic,
} from "@/lib/storytelling/easing";
import { useSceneOverrides } from "../hooks/useSceneOverrides";
import { mergePresetWithOverrides } from "../override-utils";
import { BackgroundRenderer } from "../primitives";
import { useStorytellingStore } from "../StorytellingStore";
import type { CinematicCompositionData, SceneRendererProps } from "../types";

const PointCloudStage = dynamic(
  () =>
    import("@/lib/cinematic/point-cloud-stage").then((m) => ({
      default: m.PointCloudStage,
    })),
  { ssr: false },
);

export const CinematicCompositionScene: React.FC<SceneRendererProps> = ({
  scene,
  progress,
  time,
  isActive,
  width,
  height,
  accentColor,
}) => {
  const data = scene.data as CinematicCompositionData;
  const overrides = useSceneOverrides(scene.id);

  // Resolve URLs from prerenderData (generated by orchestrator)
  const scenes = useStorytellingStore((s) => s.scenes);
  const sceneEntry = scenes.find((e) => e.scene.id === scene.id);
  const resolvedImageUrl =
    sceneEntry?.prerenderData?.imageUrl ||
    (data.imageUrl?.startsWith("GENERATE:") ? undefined : data.imageUrl);
  const resolvedDepthUrl =
    sceneEntry?.prerenderData?.depthMapUrl ||
    (data.depthUrl === "AUTO" || data.depthUrl === "auto"
      ? undefined
      : data.depthUrl);

  const basePreset = useMemo(
    () => getCinematicPreset(
      (overrides.cinematicPreset || data.preset) as CinematicPresetName | undefined,
    ),
    [data.preset, overrides.cinematicPreset],
  );
  const preset = useMemo(
    () => mergePresetWithOverrides(basePreset, overrides),
    [basePreset, overrides],
  );

  const effectiveShader = overrides.shaderVariant || data.shader;

  // Entrance dissolve
  const dissolve =
    progress < 0.08
      ? 1 - easeOutCubic(progress / 0.08)
      : progress > 0.92
        ? easeInOutCubic((progress - 0.92) / 0.08)
        : 0;

  // Staggered text entrance
  const headlineOpacity = easeOutCubic(Math.min(progress * 4, 1));
  const headlineSlide = (1 - easeOutBack(Math.min(progress * 3, 1))) * 40;
  const statOpacity = easeOutCubic(
    Math.min(Math.max(progress - 0.2, 0) * 4, 1),
  );
  const statScale = easeOutBack(Math.min(Math.max(progress - 0.2, 0) * 3, 1));
  const sourceOpacity = easeOutCubic(
    Math.min(Math.max(progress - 0.35, 0) * 4, 1),
  );

  if (!(resolvedImageUrl && resolvedDepthUrl)) {
    return (
      <BackgroundRenderer scene={scene} width={width} height={height}>
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "#555",
            fontFamily: "monospace",
            fontSize: 14,
          }}
        >
          Generating cinematic composition...
        </div>
      </BackgroundRenderer>
    );
  }

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "hidden",
      }}
    >
      {/* Full cinematic R3F canvas */}
      <div style={{ position: "absolute", inset: 0 }}>
        <PointCloudStage
          colorUrl={resolvedImageUrl}
          depthUrl={resolvedDepthUrl}
          preset={preset}
          progress={progress}
          shaderVariant={effectiveShader}
          dissolveProgress={dissolve}
        />
      </div>

      {/* Heavy vignette for composition */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          pointerEvents: "none",
          background: `radial-gradient(ellipse at center, transparent 40%, rgba(0,0,0,${preset.atmosphere.vignetteIntensity + 0.1}) 100%)`,
        }}
      />

      {/* Hero text overlay — centered composition */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          padding: "24px 32px",
          textAlign: "center",
        }}
      >
        {data.headline && (
          <h1
            style={{
              margin: 0,
              fontFamily: "Georgia, serif",
              fontSize: Math.min(width * 0.06, 42),
              fontWeight: 700,
              color: "#fff",
              lineHeight: 1.15,
              maxWidth: "80%",
              textShadow:
                "0 3px 12px rgba(0,0,0,0.7), 0 1px 4px rgba(0,0,0,0.5)",
              opacity: headlineOpacity,
              transform: `translateY(${headlineSlide}px)`,
            }}
          >
            {data.headline}
          </h1>
        )}

        {data.stat && (
          <div
            style={{
              marginTop: 20,
              padding: "8px 24px",
              background: `${accentColor}18`,
              border: `1px solid ${accentColor}33`,
              borderRadius: 6,
              fontFamily: "JetBrains Mono, monospace",
              fontSize: Math.min(width * 0.05, 36),
              fontWeight: 700,
              color: accentColor,
              letterSpacing: "-0.02em",
              textShadow: `0 0 20px ${accentColor}44`,
              opacity: statOpacity,
              transform: `scale(${statScale})`,
            }}
          >
            {data.stat}
          </div>
        )}

        {data.source && (
          <p
            style={{
              margin: "16px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 12,
              color: "rgba(255,255,255,0.45)",
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              opacity: sourceOpacity,
            }}
          >
            Source: {data.source}
          </p>
        )}
      </div>
    </div>
  );
};
