/**
 * Cinematic Flat Scene
 *
 * Clean image display with entrance animations (fade-in, zoom-in, ken-burns, etc).
 * Ported from dreams.fm FlatImageRenderer. Inline CSS — no R3F.
 */

"use client";

import type React from "react";
import { useMemo } from "react";
import { easeOutCubic } from "@/lib/storytelling/easing";
import { useSceneOverrides } from "../hooks/useSceneOverrides";
import { useStorytellingStore } from "../StorytellingStore";
import type { CinematicFlatData, SceneRendererProps } from "../types";

// ---------------------------------------------------------------------------
// CSS Keyframes
// ---------------------------------------------------------------------------

const ANIMATION_KEYFRAMES: Record<string, string> = {
  "fade-in": `
    @keyframes cfFadeIn {
      0% { opacity: 0; }
      100% { opacity: 1; }
    }
  `,
  "zoom-in": `
    @keyframes cfZoomIn {
      0% { opacity: 0; transform: scale(1.3); }
      100% { opacity: 1; transform: scale(1); }
    }
  `,
  "slide-up": `
    @keyframes cfSlideUp {
      0% { opacity: 0; transform: translateY(40px); }
      100% { opacity: 1; transform: translateY(0); }
    }
  `,
  "ken-burns": `
    @keyframes cfKenBurns {
      0% { transform: scale(1) translate(0, 0); }
      50% { transform: scale(1.12) translate(-2%, -1%); }
      100% { transform: scale(1.04) translate(1%, 0.5%); }
    }
  `,
  "parallax-drift": `
    @keyframes cfDrift {
      0% { transform: scale(1.08) translateX(0); }
      50% { transform: scale(1.08) translateX(-3%); }
      100% { transform: scale(1.08) translateX(0); }
    }
  `,
};

const ANIMATION_NAMES: Record<string, string> = {
  "fade-in": "cfFadeIn",
  "zoom-in": "cfZoomIn",
  "slide-up": "cfSlideUp",
  "ken-burns": "cfKenBurns",
  "parallax-drift": "cfDrift",
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export const CinematicFlatScene: React.FC<SceneRendererProps> = ({
  scene,
  progress,
  time,
  isActive,
  width,
  height,
  accentColor,
}) => {
  const data = scene.data as CinematicFlatData;
  const overrides = useSceneOverrides(scene.id);

  // Image stylization CSS filter from overrides
  const STYLIZATION_FILTERS: Record<string, string> = {
    none: "none",
    illustrated: "saturate(1.3) contrast(1.1) brightness(0.95)",
    editorial: "grayscale(0.4) contrast(1.15) brightness(1.05)",
    photographic: "saturate(1.1) contrast(1.05)",
    dithered: "grayscale(1) contrast(1.6) brightness(0.9)",
  };
  const stylizationFilter = STYLIZATION_FILTERS[overrides.imageStylization || "none"] || "none";

  // Resolve image URL from prerenderData (generated by orchestrator)
  const scenesStore = useStorytellingStore((s) => s.scenes);
  const sceneEntry = scenesStore.find((e) => e.scene.id === scene.id);
  const resolvedImageUrl =
    sceneEntry?.prerenderData?.imageUrl ||
    (data.imageUrl?.startsWith("GENERATE:") ? undefined : data.imageUrl);

  const animation = data.animation || "ken-burns";
  const fit = data.fit || "cover";

  const duration = useMemo(() => {
    if (animation === "ken-burns") return scene.duration || 12;
    if (animation === "parallax-drift") return scene.duration || 8;
    return 1.2;
  }, [animation, scene.duration]);

  const animName = ANIMATION_NAMES[animation] || "cfFadeIn";
  const isLooping = animation === "ken-burns" || animation === "parallax-drift";

  const textOpacity = easeOutCubic(Math.min(progress * 3, 1));
  const textSlide = (1 - easeOutCubic(Math.min(progress * 2.5, 1))) * 25;

  if (!resolvedImageUrl) {
    return (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#0a0a0a",
          color: "#555",
          fontFamily: "monospace",
          fontSize: 14,
        }}
      >
        Generating image...
      </div>
    );
  }

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "hidden",
        backgroundColor: "#0a0a0a",
      }}
    >
      <style>{ANIMATION_KEYFRAMES[animation] || ""}</style>

      {/* Image */}
      <img
        src={resolvedImageUrl}
        alt=""
        draggable={false}
        style={{
          width: "100%",
          height: "100%",
          objectFit: fit,
          animation: `${animName} ${duration}s ${isLooping ? "ease-in-out infinite alternate" : "ease-out forwards"}`,
          animationPlayState: isActive ? "running" : "paused",
          filter: stylizationFilter,
        }}
      />

      {/* Vignette */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          pointerEvents: "none",
          background:
            "radial-gradient(ellipse at center, transparent 50%, rgba(0,0,0,0.4) 100%)",
        }}
      />

      {/* Text */}
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: 0,
          right: 0,
          padding: "36px 28px 24px",
          background: "linear-gradient(transparent, rgba(0,0,0,0.7) 35%)",
          opacity: textOpacity,
          transform: `translateY(${textSlide}px)`,
        }}
      >
        {data.headline && (
          <h2
            style={{
              margin: 0,
              fontFamily: "Georgia, serif",
              fontSize: 24,
              fontWeight: 700,
              color: "#fff",
              lineHeight: 1.25,
              textShadow: "0 2px 8px rgba(0,0,0,0.5)",
            }}
          >
            {data.headline}
          </h2>
        )}
        {data.caption && (
          <p
            style={{
              margin: "6px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 14,
              color: "rgba(255,255,255,0.75)",
              lineHeight: 1.4,
            }}
          >
            {data.caption}
          </p>
        )}
        {data.source && (
          <p
            style={{
              margin: "6px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 11,
              color: "rgba(255,255,255,0.4)",
              letterSpacing: "0.05em",
              textTransform: "uppercase",
            }}
          >
            Source: {data.source}
          </p>
        )}
      </div>
    </div>
  );
};
