/**
 * Cinematic Dither Scene
 *
 * WebGL FM dithering effect — luminance-driven line displacement.
 * Ported from dreams.fm FMDitherRenderer. Inline (no R3F dependency).
 */

"use client";

import type React from "react";
import { useCallback, useEffect, useRef } from "react";
import { easeOutCubic } from "@/lib/storytelling/easing";
import { useSceneOverrides } from "../hooks/useSceneOverrides";
import { useStorytellingStore } from "../StorytellingStore";
import type { CinematicDitherData, SceneRendererProps } from "../types";

// ---------------------------------------------------------------------------
// Shaders (ported from dreams.fm FMDitherRenderer)
// ---------------------------------------------------------------------------

const FM_VERTEX_SHADER = /* glsl */ `
attribute vec2 aPosition;
attribute vec2 aTexCoord;
varying vec2 vUV;
void main() {
  vUV = aTexCoord;
  gl_Position = vec4(aPosition, 0.0, 1.0);
}
`;

const FM_FRAGMENT_SHADER = /* glsl */ `
precision highp float;
uniform sampler2D uTexture;
uniform vec2 uResolution;
uniform float uLineCount;
uniform float uAmplitude;
uniform float uFrequency;
uniform float uGlowIntensity;
uniform float uTime;
uniform int uMode;
uniform vec3 uColor;
uniform vec3 uBgColor;
varying vec2 vUV;

float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
}

void main() {
  vec2 uv = vUV;
  vec4 texColor = texture2D(uTexture, uv);
  float luma = dot(texColor.rgb, vec3(0.299, 0.587, 0.114));
  float result = 0.0;

  if (uMode == 0) {
    float lineY = fract(uv.y * uLineCount);
    float wave = sin((uv.x + uTime * 0.1) * uFrequency) * uAmplitude * luma;
    float dist = abs(lineY - 0.5 + wave);
    float lineThickness = 0.15 + luma * 0.35;
    result = smoothstep(lineThickness, lineThickness - 0.05, dist);
  } else if (uMode == 1) {
    float lineX = fract(uv.x * uLineCount);
    float wave = sin((uv.y + uTime * 0.1) * uFrequency) * uAmplitude * luma;
    float dist = abs(lineX - 0.5 + wave);
    float lineThickness = 0.15 + luma * 0.35;
    result = smoothstep(lineThickness, lineThickness - 0.05, dist);
  } else if (uMode == 2) {
    vec2 cell = floor(uv * uLineCount);
    vec2 cellUV = fract(uv * uLineCount);
    float noise = hash(cell + floor(uTime * 0.5));
    float threshold = luma * 0.8 + noise * 0.2;
    float dist = length(cellUV - 0.5);
    result = smoothstep(threshold * 0.5, threshold * 0.5 - 0.05, dist);
  } else {
    float noise = hash(uv * uResolution + vec2(uTime * 10.0));
    result = step(noise, luma);
    float scanline = sin(uv.y * uResolution.y * 0.5) * 0.1;
    result *= 0.9 + scanline;
  }

  float glow = result * uGlowIntensity;
  vec3 color = mix(uBgColor, uColor, result);
  color += uColor * glow * 0.3;
  gl_FragColor = vec4(color, 1.0);
}
`;

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export const CinematicDitherScene: React.FC<SceneRendererProps> = ({
  scene,
  progress,
  time,
  isActive,
  width,
  height,
  accentColor,
}) => {
  const data = scene.data as CinematicDitherData;
  const overrides = useSceneOverrides(scene.id);

  // Effective values: overrides > data > defaults
  const effectiveMode = overrides.ditherMode || data.mode || "verticalFM";
  const effectiveLineCount = overrides.ditherLineCount ?? data.lineCount ?? 140;
  const effectiveAmplitude = overrides.ditherAmplitude ?? data.amplitude ?? 0.3;
  const effectiveFrequency = overrides.ditherFrequency ?? data.frequency ?? 20;
  const effectiveGlow = overrides.ditherGlow ?? data.glow ?? 0.5;
  const effectiveColor = overrides.ditherColor || data.color || accentColor || "#22d3ee";

  // Resolve image URL from prerenderData (generated by orchestrator)
  const scenes = useStorytellingStore((s) => s.scenes);
  const sceneEntry = scenes.find((e) => e.scene.id === scene.id);
  const resolvedImageUrl =
    sceneEntry?.prerenderData?.imageUrl ||
    (data.imageUrl?.startsWith("GENERATE:") ? undefined : data.imageUrl);

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const glRef = useRef<WebGLRenderingContext | null>(null);
  const programRef = useRef<WebGLProgram | null>(null);
  const textureRef = useRef<WebGLTexture | null>(null);
  const buffersRef = useRef<WebGLBuffer[]>([]);
  const shadersRef = useRef<WebGLShader[]>([]);
  const frameRef = useRef<number>(0);
  const timeRef = useRef(0);

  const compileShader = useCallback(
    (gl: WebGLRenderingContext, src: string, type: number) => {
      const shader = gl.createShader(type)!;
      gl.shaderSource(shader, src);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        console.warn(
          "[CinematicDither] Shader error:",
          gl.getShaderInfoLog(shader),
        );
        gl.deleteShader(shader);
        return null;
      }
      return shader;
    },
    [],
  );

  const cleanup = useCallback(() => {
    if (frameRef.current) cancelAnimationFrame(frameRef.current);
    const gl = glRef.current;
    if (gl) {
      if (textureRef.current) gl.deleteTexture(textureRef.current);
      for (const buf of buffersRef.current) gl.deleteBuffer(buf);
      for (const sh of shadersRef.current) gl.deleteShader(sh);
      if (programRef.current) gl.deleteProgram(programRef.current);
    }
    textureRef.current = null;
    buffersRef.current = [];
    shadersRef.current = [];
    programRef.current = null;
    glRef.current = null;
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!(canvas && resolvedImageUrl)) return;

    // Handle WebGL context loss gracefully
    const handleContextLost = (e: Event) => {
      e.preventDefault();
      console.warn("[CinematicDither] WebGL context lost — will restore when available");
      if (frameRef.current) cancelAnimationFrame(frameRef.current);
    };
    const handleContextRestored = () => {
      console.log("[CinematicDither] WebGL context restored");
      // Re-initialization will happen on next effect cycle
    };
    canvas.addEventListener("webglcontextlost", handleContextLost);
    canvas.addEventListener("webglcontextrestored", handleContextRestored);

    cleanup();

    const gl = canvas.getContext("webgl", { alpha: false, antialias: false });
    if (!gl) return;
    glRef.current = gl;

    const vs = compileShader(gl, FM_VERTEX_SHADER, gl.VERTEX_SHADER);
    const fs = compileShader(gl, FM_FRAGMENT_SHADER, gl.FRAGMENT_SHADER);
    if (!(vs && fs)) return;
    shadersRef.current = [vs, fs];

    const program = gl.createProgram()!;
    gl.attachShader(program, vs);
    gl.attachShader(program, fs);
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) return;
    programRef.current = program;
    gl.useProgram(program);

    // Full-screen quad
    const positions = new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]);
    const texCoords = new Float32Array([0, 1, 1, 1, 0, 0, 1, 0]);

    const posBuf = gl.createBuffer()!;
    gl.bindBuffer(gl.ARRAY_BUFFER, posBuf);
    gl.bufferData(gl.ARRAY_BUFFER, positions, gl.STATIC_DRAW);
    const posLoc = gl.getAttribLocation(program, "aPosition");
    gl.enableVertexAttribArray(posLoc);
    gl.vertexAttribPointer(posLoc, 2, gl.FLOAT, false, 0, 0);

    const texBuf = gl.createBuffer()!;
    gl.bindBuffer(gl.ARRAY_BUFFER, texBuf);
    gl.bufferData(gl.ARRAY_BUFFER, texCoords, gl.STATIC_DRAW);
    const texLoc = gl.getAttribLocation(program, "aTexCoord");
    gl.enableVertexAttribArray(texLoc);
    gl.vertexAttribPointer(texLoc, 2, gl.FLOAT, false, 0, 0);
    buffersRef.current = [posBuf, texBuf];

    // Load image texture
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      if (!(glRef.current && programRef.current)) return;

      canvas.width = img.width;
      canvas.height = img.height;
      gl.viewport(0, 0, img.width, img.height);

      const tex = gl.createTexture()!;
      gl.bindTexture(gl.TEXTURE_2D, tex);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, img);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
      textureRef.current = tex;

      gl.uniform1i(gl.getUniformLocation(program, "uTexture"), 0);
      gl.uniform2f(
        gl.getUniformLocation(program, "uResolution"),
        img.width,
        img.height,
      );
      gl.uniform1f(
        gl.getUniformLocation(program, "uLineCount"),
        effectiveLineCount,
      );
      gl.uniform1f(
        gl.getUniformLocation(program, "uAmplitude"),
        effectiveAmplitude,
      );
      gl.uniform1f(gl.getUniformLocation(program, "uFrequency"), effectiveFrequency);
      gl.uniform1f(gl.getUniformLocation(program, "uGlowIntensity"), effectiveGlow);

      const modes: Record<string, number> = {
        verticalFM: 0,
        horizontalFM: 1,
        scatter: 2,
        noise: 3,
      };
      gl.uniform1i(
        gl.getUniformLocation(program, "uMode"),
        modes[effectiveMode] ?? 0,
      );

      const parseHex = (hex: string) => {
        const c = hex.replace("#", "");
        return [
          Number.parseInt(c.slice(0, 2), 16) / 255,
          Number.parseInt(c.slice(2, 4), 16) / 255,
          Number.parseInt(c.slice(4, 6), 16) / 255,
        ];
      };
      const col = parseHex(effectiveColor);
      const bg = parseHex("#0a0a0a");
      gl.uniform3f(
        gl.getUniformLocation(program, "uColor"),
        col[0],
        col[1],
        col[2],
      );
      gl.uniform3f(
        gl.getUniformLocation(program, "uBgColor"),
        bg[0],
        bg[1],
        bg[2],
      );

      // Cache uniform location to avoid per-frame string lookup
      const uTimeLoc = gl.getUniformLocation(program, "uTime");
      const animate = () => {
        if (!(glRef.current && programRef.current)) return;
        frameRef.current = requestAnimationFrame(animate);
        timeRef.current += 1 / 60;
        gl.uniform1f(uTimeLoc, timeRef.current);
        gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
      };
      animate();
    };
    img.src = resolvedImageUrl;

    return () => {
      canvas.removeEventListener("webglcontextlost", handleContextLost);
      canvas.removeEventListener("webglcontextrestored", handleContextRestored);
      cleanup();
    };
  }, [
    resolvedImageUrl,
    effectiveMode,
    effectiveLineCount,
    effectiveAmplitude,
    effectiveFrequency,
    effectiveGlow,
    effectiveColor,
    compileShader,
    cleanup,
  ]);

  const textOpacity = easeOutCubic(Math.min(progress * 3, 1));

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "hidden",
        backgroundColor: "#0a0a0a",
      }}
    >
      {resolvedImageUrl ? (
        <canvas
          ref={canvasRef}
          style={{ width: "100%", height: "100%", objectFit: "cover" }}
        />
      ) : (
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "#555",
            fontFamily: "monospace",
            fontSize: 14,
          }}
        >
          Generating dither image...
        </div>
      )}

      {/* Text overlay */}
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: 0,
          right: 0,
          padding: "36px 28px 24px",
          background: "linear-gradient(transparent, rgba(10,10,10,0.85) 40%)",
          opacity: textOpacity,
        }}
      >
        {data.headline && (
          <h2
            style={{
              margin: 0,
              fontFamily: "JetBrains Mono, monospace",
              fontSize: 22,
              fontWeight: 700,
              color: effectiveColor,
              lineHeight: 1.2,
              textShadow: `0 0 12px ${effectiveColor}44`,
            }}
          >
            {data.headline}
          </h2>
        )}
        {data.caption && (
          <p
            style={{
              margin: "6px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 13,
              color: "rgba(255,255,255,0.6)",
              lineHeight: 1.4,
            }}
          >
            {data.caption}
          </p>
        )}
      </div>
    </div>
  );
};
