/**
 * Cinematic Point Cloud Scene
 *
 * Renders an image as a GPU-driven 3D point cloud with dissolve transitions,
 * orbital camera, and atmosphere particles. Uses R3F via dynamic import.
 */

"use client";

import dynamic from "next/dynamic";
import type React from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  type CinematicPresetName,
  getCinematicPreset,
} from "@/lib/cinematic/scene-presets";
import { easeInOutCubic, easeOutCubic } from "@/lib/storytelling/easing";
import { useSceneOverrides } from "../hooks/useSceneOverrides";
import { mergePresetWithOverrides } from "../override-utils";
import { BackgroundRenderer } from "../primitives";
import { useStorytellingStore } from "../StorytellingStore";
import type { CinematicPointCloudData, SceneRendererProps } from "../types";

const PointCloudStage = dynamic(
  () =>
    import("@/lib/cinematic/point-cloud-stage").then((m) => ({
      default: m.PointCloudStage,
    })),
  { ssr: false },
);

export const CinematicPointCloudScene: React.FC<SceneRendererProps> = ({
  scene,
  progress,
  time,
  isActive,
  width,
  height,
  accentColor,
}) => {
  const data = scene.data as CinematicPointCloudData;
  const overrides = useSceneOverrides(scene.id);

  // Resolve URLs from prerenderData (generated by orchestrator)
  const scenes = useStorytellingStore((s) => s.scenes);
  const sceneEntry = scenes.find((e) => e.scene.id === scene.id);
  const resolvedImageUrl =
    sceneEntry?.prerenderData?.imageUrl ||
    (data.imageUrl?.startsWith("GENERATE:") ? undefined : data.imageUrl);
  const resolvedDepthUrl =
    sceneEntry?.prerenderData?.depthMapUrl ||
    (data.depthUrl === "AUTO" || data.depthUrl === "auto"
      ? undefined
      : data.depthUrl);

  const basePreset = useMemo(
    () => getCinematicPreset(
      (overrides.cinematicPreset || data.preset) as CinematicPresetName | undefined,
    ),
    [data.preset, overrides.cinematicPreset],
  );
  const preset = useMemo(
    () => mergePresetWithOverrides(basePreset, overrides),
    [basePreset, overrides],
  );

  const effectiveShader = overrides.shaderVariant || data.shader;

  // 8s fallback: if image is ready but depth never arrives, use CSS parallax
  const [depthTimedOut, setDepthTimedOut] = useState(false);
  const depthTimeoutRef = useRef<ReturnType<typeof setTimeout>>();
  useEffect(() => {
    if (resolvedDepthUrl || !resolvedImageUrl) {
      setDepthTimedOut(false);
      if (depthTimeoutRef.current) clearTimeout(depthTimeoutRef.current);
      return;
    }
    depthTimeoutRef.current = setTimeout(() => {
      console.warn("[PointCloud] Depth timed out for scene", scene.id, "— using CSS fallback");
      setDepthTimedOut(true);
    }, 8000);
    return () => { if (depthTimeoutRef.current) clearTimeout(depthTimeoutRef.current); };
  }, [resolvedImageUrl, resolvedDepthUrl, scene.id]);

  // Dissolve in at start, out at end
  const dissolve =
    progress < 0.1
      ? 1 - easeOutCubic(progress / 0.1)
      : progress > 0.9
        ? easeInOutCubic((progress - 0.9) / 0.1)
        : 0;

  const textOpacity = easeOutCubic(Math.min(progress * 3, 1));
  const textSlide = (1 - easeOutCubic(Math.min(progress * 2.5, 1))) * 30;

  // CSS parallax fallback when depth timed out but image is available
  if (resolvedImageUrl && depthTimedOut && !resolvedDepthUrl) {
    const kenBurnsProgress = progress;
    const scale = 1.05 + kenBurnsProgress * 0.08;
    const tx = Math.sin(kenBurnsProgress * Math.PI) * 2;
    const ty = Math.cos(kenBurnsProgress * Math.PI * 0.7) * 1.5;
    return (
      <div style={{ position: "relative", width: "100%", height: "100%", overflow: "hidden", backgroundColor: "#0a0a0a" }}>
        <img
          src={resolvedImageUrl}
          alt=""
          draggable={false}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "cover",
            transform: `scale(${scale}) translate(${tx}%, ${ty}%)`,
            transition: "transform 0.3s ease-out",
          }}
        />
        <div style={{ position: "absolute", inset: 0, pointerEvents: "none", background: `radial-gradient(ellipse at center, transparent 50%, rgba(0,0,0,${preset.atmosphere.vignetteIntensity}) 100%)` }} />
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, padding: "40px 32px 32px", background: "linear-gradient(transparent, rgba(0,0,0,0.7) 40%)", opacity: textOpacity, transform: `translateY(${textSlide}px)` }}>
          {data.headline && <h2 style={{ margin: 0, fontFamily: "Georgia, serif", fontSize: 28, fontWeight: 700, color: "#fff", lineHeight: 1.2, textShadow: "0 2px 8px rgba(0,0,0,0.6)" }}>{data.headline}</h2>}
          {data.caption && <p style={{ margin: "8px 0 0", fontFamily: "system-ui, sans-serif", fontSize: 15, color: "rgba(255,255,255,0.8)", lineHeight: 1.4 }}>{data.caption}</p>}
          {data.stat && <div style={{ marginTop: 12, display: "inline-block", padding: "6px 16px", background: `${accentColor}22`, border: `1px solid ${accentColor}44`, borderRadius: 4, fontFamily: "JetBrains Mono, monospace", fontSize: 22, fontWeight: 700, color: accentColor }}>{data.stat}</div>}
        </div>
      </div>
    );
  }

  if (!(resolvedImageUrl && resolvedDepthUrl)) {
    return (
      <BackgroundRenderer scene={scene} width={width} height={height}>
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "#555",
            fontFamily: "monospace",
            fontSize: 14,
          }}
        >
          Generating point cloud...
        </div>
      </BackgroundRenderer>
    );
  }

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "hidden",
      }}
    >
      {/* R3F Point Cloud */}
      <div style={{ position: "absolute", inset: 0 }}>
        <PointCloudStage
          colorUrl={resolvedImageUrl}
          depthUrl={resolvedDepthUrl}
          preset={preset}
          progress={progress}
          shaderVariant={effectiveShader}
          dissolveProgress={dissolve}
        />
      </div>

      {/* Vignette overlay */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          pointerEvents: "none",
          background: `radial-gradient(ellipse at center, transparent 50%, rgba(0,0,0,${preset.atmosphere.vignetteIntensity}) 100%)`,
        }}
      />

      {/* Text overlay */}
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: 0,
          right: 0,
          padding: "40px 32px 32px",
          background: "linear-gradient(transparent, rgba(0,0,0,0.7) 40%)",
          opacity: textOpacity,
          transform: `translateY(${textSlide}px)`,
          transition: "opacity 0.3s ease",
        }}
      >
        {data.headline && (
          <h2
            style={{
              margin: 0,
              fontFamily: "Georgia, serif",
              fontSize: 28,
              fontWeight: 700,
              color: "#fff",
              lineHeight: 1.2,
              textShadow: "0 2px 8px rgba(0,0,0,0.6)",
            }}
          >
            {data.headline}
          </h2>
        )}
        {data.caption && (
          <p
            style={{
              margin: "8px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 15,
              color: "rgba(255,255,255,0.8)",
              lineHeight: 1.4,
              textShadow: "0 1px 4px rgba(0,0,0,0.5)",
            }}
          >
            {data.caption}
          </p>
        )}
        {data.stat && (
          <div
            style={{
              marginTop: 12,
              display: "inline-block",
              padding: "6px 16px",
              background: `${accentColor}22`,
              border: `1px solid ${accentColor}44`,
              borderRadius: 4,
              fontFamily: "JetBrains Mono, monospace",
              fontSize: 22,
              fontWeight: 700,
              color: accentColor,
            }}
          >
            {data.stat}
          </div>
        )}
        {data.source && (
          <p
            style={{
              margin: "8px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 11,
              color: "rgba(255,255,255,0.4)",
              letterSpacing: "0.05em",
              textTransform: "uppercase",
            }}
          >
            Source: {data.source}
          </p>
        )}
      </div>
    </div>
  );
};
