/**
 * Cinematic Layered Scene
 *
 * Multi-layer RGBA planes with parallax depth offsets.
 * Each layer moves at a different speed based on its depth position.
 * Pure CSS — no R3F dependency.
 */

"use client";

import type React from "react";
import { easeInOutCubic, easeOutCubic } from "@/lib/storytelling/easing";
import { BackgroundRenderer } from "../primitives";
import { useStorytellingStore } from "../StorytellingStore";
import type { CinematicLayeredData, SceneRendererProps } from "../types";

export const CinematicLayeredScene: React.FC<SceneRendererProps> = ({
  scene,
  progress,
  time,
  isActive,
  width,
  height,
  accentColor,
}) => {
  const data = scene.data as CinematicLayeredData;

  // Resolve image URL from prerenderData (generated by orchestrator)
  const scenesStore = useStorytellingStore((s) => s.scenes);
  const sceneEntry = scenesStore.find((e) => e.scene.id === scene.id);
  const resolvedImageUrl =
    sceneEntry?.prerenderData?.imageUrl ||
    (data.imageUrl?.startsWith("GENERATE:") ? undefined : data.imageUrl);

  const fadeIn = easeOutCubic(Math.min(progress * 4, 1));
  const textOpacity = easeOutCubic(
    Math.min(Math.max(progress - 0.15, 0) * 4, 1),
  );

  const layers = data.layers || [];

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        overflow: "hidden",
        backgroundColor: "#0a0a0a",
      }}
    >
      {/* Base image */}
      {resolvedImageUrl && (
        <img
          src={resolvedImageUrl}
          alt=""
          draggable={false}
          style={{
            position: "absolute",
            inset: 0,
            width: "100%",
            height: "100%",
            objectFit: "cover",
            opacity: fadeIn * 0.3,
            filter: "blur(4px) brightness(0.6)",
          }}
        />
      )}

      {/* Parallax layers */}
      {layers.map((layer, i) => {
        // Skip layers with placeholder URLs
        if (!layer.url || layer.url.startsWith("GENERATE:")) return null;
        const depth = layer.depth ?? (i + 1) / (layers.length + 1);
        // Deeper layers move slower (parallax)
        const parallaxX =
          Math.sin(progress * Math.PI * 0.8 + i) * (1 - depth) * 40;
        const parallaxY =
          Math.cos(progress * Math.PI * 0.4 + i * 0.5) * (1 - depth) * 20;
        const scale = 1 + depth * 0.1 + progress * 0.05;

        return (
          <div
            key={i}
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              transform: `translate(${parallaxX}px, ${parallaxY}px) scale(${scale})`,
              opacity: fadeIn,
              transition: "transform 0.1s linear",
            }}
          >
            <img
              src={layer.url}
              alt=""
              draggable={false}
              style={{
                maxWidth: "100%",
                maxHeight: "100%",
                objectFit: "contain",
              }}
            />
          </div>
        );
      })}

      {/* Vignette */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          pointerEvents: "none",
          background:
            "radial-gradient(ellipse at center, transparent 45%, rgba(0,0,0,0.5) 100%)",
        }}
      />

      {/* Text */}
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: 0,
          right: 0,
          padding: "36px 28px 24px",
          background: "linear-gradient(transparent, rgba(0,0,0,0.65) 35%)",
          opacity: textOpacity,
        }}
      >
        {data.headline && (
          <h2
            style={{
              margin: 0,
              fontFamily: "Georgia, serif",
              fontSize: 24,
              fontWeight: 700,
              color: "#fff",
              lineHeight: 1.25,
              textShadow: "0 2px 6px rgba(0,0,0,0.5)",
            }}
          >
            {data.headline}
          </h2>
        )}
        {data.caption && (
          <p
            style={{
              margin: "6px 0 0",
              fontFamily: "system-ui, sans-serif",
              fontSize: 14,
              color: "rgba(255,255,255,0.75)",
              lineHeight: 1.4,
            }}
          >
            {data.caption}
          </p>
        )}
      </div>
    </div>
  );
};
