/**
 * Format templates for different research paper styles
 */

export interface FormatTemplate {
  label: string;
  description: string;
  structure: string[];
  fontFamily: string;
  fontSize: string;
  lineHeight: string;
  icon: string;
}

export const formatTemplates: Record<'academic' | 'blog' | 'technical-report', FormatTemplate> = {
  academic: {
    label: 'Academic Paper',
    description: 'Formal research paper with abstract, methodology, and references',
    structure: [
      '# [Paper Title]',
      '',
      '**Authors:** [Author Names]',
      '',
      '**Affiliation:** [Institution/Organization]',
      '',
      '**Date:** [Publication Date]',
      '',
      '---',
      '',
      '## Abstract',
      '',
      '[Brief summary of the research, typically 150-250 words]',
      '',
      '**Keywords:** [keyword1, keyword2, keyword3]',
      '',
      '---',
      '',
      '## 1. Introduction',
      '',
      '[Background and context of the research]',
      '',
      '### 1.1 Research Problem',
      '',
      '[Define the problem being addressed]',
      '',
      '### 1.2 Research Questions',
      '',
      '[List key research questions]',
      '',
      '### 1.3 Objectives',
      '',
      '[State the objectives of the study]',
      '',
      '## 2. Literature Review',
      '',
      '[Review of existing research and theoretical framework]',
      '',
      '## 3. Methodology',
      '',
      '### 3.1 Research Design',
      '',
      '[Describe the research approach]',
      '',
      '### 3.2 Data Collection',
      '',
      '[Explain data collection methods]',
      '',
      '### 3.3 Analysis Methods',
      '',
      '[Detail analysis techniques]',
      '',
      '## 4. Results',
      '',
      '[Present findings with supporting data]',
      '',
      '## 5. Discussion',
      '',
      '### 5.1 Interpretation',
      '',
      '[Interpret the results]',
      '',
      '### 5.2 Implications',
      '',
      '[Discuss theoretical and practical implications]',
      '',
      '### 5.3 Limitations',
      '',
      '[Acknowledge study limitations]',
      '',
      '## 6. Conclusion',
      '',
      '[Summarize key findings and future directions]',
      '',
      '## 7. References',
      '',
      '[List all cited sources in appropriate format]',
      '',
      '---',
      '',
      '## Appendices',
      '',
      '[Supplementary materials if needed]',
    ],
    fontFamily: 'serif',
    fontSize: '12pt',
    lineHeight: '2.0',
    icon: 'Article',
  },

  blog: {
    label: 'Blog Post',
    description: 'Engaging, conversational content for general audiences',
    structure: [
      '# [Catchy, Engaging Title]',
      '',
      '![Featured Image](image-url-here)',
      '',
      '*Published on [Date] by [Author Name]*',
      '',
      '---',
      '',
      '## Introduction',
      '',
      '[Hook the reader with an interesting opening. Tell them why this topic matters.]',
      '',
      '**TL;DR:** [Quick summary for skimmers]',
      '',
      '## The Problem/Context',
      '',
      '[Explain the issue or background]',
      '',
      '## Main Point 1',
      '',
      '[First key insight or section]',
      '',
      '### Supporting Details',
      '',
      '[Expand on the point with examples, data, or stories]',
      '',
      '## Main Point 2',
      '',
      '[Second key insight]',
      '',
      '### Real-World Example',
      '',
      '[Provide concrete examples or case studies]',
      '',
      '## Main Point 3',
      '',
      '[Third key insight]',
      '',
      '### Actionable Takeaways',
      '',
      '[Give readers practical tips they can use]',
      '',
      '## Conclusion',
      '',
      '[Wrap up with key insights and call-to-action]',
      '',
      '### Key Takeaways',
      '',
      '- [Bullet point 1]',
      '- [Bullet point 2]',
      '- [Bullet point 3]',
      '',
      '---',
      '',
      '## Further Reading',
      '',
      '- [Resource 1](link)',
      '- [Resource 2](link)',
      '- [Resource 3](link)',
      '',
      '---',
      '',
      '*What are your thoughts? Share in the comments below!*',
    ],
    fontFamily: 'sans-serif',
    fontSize: '16pt',
    lineHeight: '1.6',
    icon: 'Newspaper',
  },

  'technical-report': {
    label: 'Technical Report',
    description: 'Detailed technical documentation with specifications and implementation details',
    structure: [
      '# [Technical Report Title]',
      '',
      '**Project:** [Project Name]',
      '',
      '**Version:** [Version Number]',
      '',
      '**Date:** [Report Date]',
      '',
      '**Authors:** [Author Names and Roles]',
      '',
      '---',
      '',
      '## Executive Summary',
      '',
      '[High-level overview for decision-makers, 1-2 paragraphs]',
      '',
      '### Key Findings',
      '',
      '- [Finding 1]',
      '- [Finding 2]',
      '- [Finding 3]',
      '',
      '---',
      '',
      '## Table of Contents',
      '',
      '1. Executive Summary',
      '2. Technical Background',
      '3. System Architecture',
      '4. Implementation Details',
      '5. Testing & Validation',
      '6. Performance Analysis',
      '7. Recommendations',
      '8. References',
      '',
      '---',
      '',
      '## 1. Technical Background',
      '',
      '### 1.1 Context',
      '',
      '[Explain the technical context and requirements]',
      '',
      '### 1.2 Scope',
      '',
      '[Define what is and is not included]',
      '',
      '### 1.3 Assumptions',
      '',
      '[List technical assumptions]',
      '',
      '## 2. System Architecture',
      '',
      '### 2.1 Overview',
      '',
      '[High-level architecture description]',
      '',
      '```',
      '[Architecture Diagram]',
      '```',
      '',
      '### 2.2 Components',
      '',
      '[Describe system components]',
      '',
      '### 2.3 Data Flow',
      '',
      '[Explain how data moves through the system]',
      '',
      '## 3. Implementation Details',
      '',
      '### 3.1 Technologies Used',
      '',
      '- **Language:** [Programming language]',
      '- **Framework:** [Framework name]',
      '- **Database:** [Database system]',
      '- **Tools:** [Development tools]',
      '',
      '### 3.2 Code Structure',
      '',
      '```',
      '[Code examples or pseudocode]',
      '```',
      '',
      '### 3.3 Configuration',
      '',
      '[Configuration details and environment setup]',
      '',
      '## 4. Testing & Validation',
      '',
      '### 4.1 Test Strategy',
      '',
      '[Describe testing approach]',
      '',
      '### 4.2 Test Results',
      '',
      '[Present test outcomes]',
      '',
      '### 4.3 Known Issues',
      '',
      '[List any known bugs or limitations]',
      '',
      '## 5. Performance Analysis',
      '',
      '### 5.1 Metrics',
      '',
      '[Performance measurements]',
      '',
      '### 5.2 Benchmarks',
      '',
      '[Benchmark results]',
      '',
      '### 5.3 Optimization Opportunities',
      '',
      '[Potential improvements]',
      '',
      '## 6. Recommendations',
      '',
      '### 6.1 Short-term Actions',
      '',
      '[Immediate next steps]',
      '',
      '### 6.2 Long-term Strategy',
      '',
      '[Future considerations]',
      '',
      '### 6.3 Risk Mitigation',
      '',
      '[Identified risks and mitigation strategies]',
      '',
      '## 7. References',
      '',
      '### Technical Documentation',
      '',
      '- [Reference 1]',
      '- [Reference 2]',
      '',
      '### Standards & Specifications',
      '',
      '- [Standard 1]',
      '- [Standard 2]',
      '',
      '---',
      '',
      '## Appendices',
      '',
      '### Appendix A: Detailed Specifications',
      '',
      '[Technical specifications]',
      '',
      '### Appendix B: Code Listings',
      '',
      '[Full code if needed]',
      '',
      '### Appendix C: Test Data',
      '',
      '[Sample data sets]',
    ],
    fontFamily: 'monospace',
    fontSize: '14pt',
    lineHeight: '1.5',
    icon: 'FileCode',
  },
};

/**
 * Get template structure as string
 */
export function getTemplateString(format: 'academic' | 'blog' | 'technical-report'): string {
  return formatTemplates[format].structure.join('\n');
}

/**
 * Get format-specific CSS class
 */
export function getFormatClass(format: 'academic' | 'blog' | 'technical-report'): string {
  const formatClasses = {
    academic: 'font-serif text-sm leading-loose',
    blog: 'font-sans text-base leading-relaxed',
    'technical-report': 'font-mono text-sm leading-normal',
  };
  return formatClasses[format];
}

/**
 * Get word count expectations by format
 */
export function getFormatWordCountRange(format: 'academic' | 'blog' | 'technical-report'): { min: number; max: number } {
  const ranges = {
    academic: { min: 3000, max: 8000 },
    blog: { min: 1000, max: 3000 },
    'technical-report': { min: 2000, max: 5000 },
  };
  return ranges[format];
}
